# coding: utf-8

"""
    ReEarth-CMS Integration API

    ReEarth-CMS Integration API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from reearthcmsapi.paths.projects_project_id_assets.post import AssetCreate
from reearthcmsapi.paths.projects_project_id_assets.get import AssetFilter


class AssetsProjectApi(
    AssetCreate,
    AssetFilter,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
