# coding: utf-8

"""
    ReEarth-CMS Integration API

    ReEarth-CMS Integration API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from reearthcmsapi.paths.assets_asset_id_comments.post import AssetCommentCreate
from reearthcmsapi.paths.assets_asset_id_comments_comment_id.delete import AssetCommentDelete
from reearthcmsapi.paths.assets_asset_id_comments.get import AssetCommentList
from reearthcmsapi.paths.assets_asset_id_comments_comment_id.patch import AssetCommentUpdate


class AssetsCommentsApi(
    AssetCommentCreate,
    AssetCommentDelete,
    AssetCommentList,
    AssetCommentUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
