# coding: utf-8

"""
    ReEarth-CMS Integration API

    ReEarth-CMS Integration API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from reearthcmsapi.paths.models_model_id_items.post import ItemCreate
from reearthcmsapi.paths.items_item_id.delete import ItemDelete
from reearthcmsapi.paths.models_model_id_items.get import ItemFilter
from reearthcmsapi.paths.items_item_id.get import ItemGet
from reearthcmsapi.paths.items_item_id.patch import ItemUpdate


class ItemsApi(
    ItemCreate,
    ItemDelete,
    ItemFilter,
    ItemGet,
    ItemUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
