# coding: utf-8

"""
    ReEarth-CMS Integration API

    ReEarth-CMS Integration API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from reearthcmsapi.paths.models_model_id.get import ModelGet
from reearthcmsapi.paths.projects_project_id_or_alias_models_model_id_or_key.get import ModelGetWithProject


class ModelsApi(
    ModelGet,
    ModelGetWithProject,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
