# coding: utf-8

"""
    ReEarth-CMS Integration API

    ReEarth-CMS Integration API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import reearthcmsapi
from reearthcmsapi.model.asset_embedding import AssetEmbedding
from reearthcmsapi import configuration


class TestAssetEmbedding(unittest.TestCase):
    """AssetEmbedding unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
