# coding: utf-8

"""
    ReEarth-CMS Integration API

    ReEarth-CMS Integration API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from reearthcmsapi import schemas  # noqa: F401


class ValueType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    @schemas.classproperty
    def TEXT(cls):
        return cls("text")
    
    @schemas.classproperty
    def TEXT_AREA(cls):
        return cls("textArea")
    
    @schemas.classproperty
    def RICH_TEXT(cls):
        return cls("richText")
    
    @schemas.classproperty
    def MARKDOWN(cls):
        return cls("markdown")
    
    @schemas.classproperty
    def ASSET(cls):
        return cls("asset")
    
    @schemas.classproperty
    def DATE(cls):
        return cls("date")
    
    @schemas.classproperty
    def BOOL(cls):
        return cls("bool")
    
    @schemas.classproperty
    def SELECT(cls):
        return cls("select")
    
    @schemas.classproperty
    def TAG(cls):
        return cls("tag")
    
    @schemas.classproperty
    def INTEGER(cls):
        return cls("integer")
    
    @schemas.classproperty
    def REFERENCE(cls):
        return cls("reference")
    
    @schemas.classproperty
    def URL(cls):
        return cls("url")
